// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpYr9yb65KFmGuCZ9N8R5-u8-yC7xnRZY',
    appId: '1:97009830636:web:1bf2075f2594121b75f3c9',
    messagingSenderId: '97009830636',
    projectId: 'fall-detection-ac8ac',
    authDomain: 'fall-detection-ac8ac.firebaseapp.com',
    databaseURL: 'https://fall-detection-ac8ac-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fall-detection-ac8ac.firebasestorage.app',
    measurementId: 'G-H961YHXV5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQDbjZMSlc5dxztRxcaUl95P7n3-Eotds',
    appId: '1:97009830636:android:5276a50a85dc4fc575f3c9',
    messagingSenderId: '97009830636',
    projectId: 'fall-detection-ac8ac',
    databaseURL: 'https://fall-detection-ac8ac-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fall-detection-ac8ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs4O4O23Kzbeu-s_trs7G1OJBXQHYmWM0',
    appId: '1:97009830636:ios:a8ee3a81f88e8da375f3c9',
    messagingSenderId: '97009830636',
    projectId: 'fall-detection-ac8ac',
    databaseURL: 'https://fall-detection-ac8ac-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fall-detection-ac8ac.firebasestorage.app',
    iosBundleId: 'com.example.fallDetectionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs4O4O23Kzbeu-s_trs7G1OJBXQHYmWM0',
    appId: '1:97009830636:ios:a8ee3a81f88e8da375f3c9',
    messagingSenderId: '97009830636',
    projectId: 'fall-detection-ac8ac',
    databaseURL: 'https://fall-detection-ac8ac-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fall-detection-ac8ac.firebasestorage.app',
    iosBundleId: 'com.example.fallDetectionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpYr9yb65KFmGuCZ9N8R5-u8-yC7xnRZY',
    appId: '1:97009830636:web:bc838e2d8eb7be6775f3c9',
    messagingSenderId: '97009830636',
    projectId: 'fall-detection-ac8ac',
    authDomain: 'fall-detection-ac8ac.firebaseapp.com',
    databaseURL: 'https://fall-detection-ac8ac-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fall-detection-ac8ac.firebasestorage.app',
    measurementId: 'G-FQXVW0FCLN',
  );
}
